/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#ffffff",
        foreground: "#0c090c",
        card: "#ffffff",
        "card-foreground": "#0c090c",
        primary: "#a800b7",
        "primary-foreground": "#fdf4ff",
        secondary: "#f3f1f3",
        "secondary-foreground": "#0c090c",
        muted: "#f3f1f3",
        "muted-foreground": "#79697b",
        accent: "#f3f1f3",
        "accent-foreground": "#0c090c",
        destructive: "#e7000b",
        border: "#e7e4e7",
        input: "#e7e4e7",
        ring: "#a89ea9",
        sidebar: "#fafafa",
        "sidebar-foreground": "#0c090c",
        "sidebar-primary": "#a800b7",
        "sidebar-primary-foreground": "#fdf4ff",
        "sidebar-accent": "#f3f1f3",
        "sidebar-border": "#e7e4e7",
      },
    },
  },
  plugins: [],
};
